DROP DATABASE IF EXISTS dmall;
CREATE DATABASE dmall DEFAULT CHARSET utf8;
USE dmall;

DROP TABLE IF EXISTS user_info;
CREATE TABLE user_info (
  id INT NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  username VARCHAR(50) NOT NULL COMMENT '用户名',
  password VARCHAR(50) NOT NULL COMMENT '用户密码MD5',
  salt VARCHAR(50) NOT NULL COMMENT '用户密码盐值',
  email VARCHAR(50) DEFAULT NULL COMMENT '用户邮箱',
  phone VARCHAR(20) DEFAULT NULL COMMENT '用户联系电话',
  logistics_id BIGINT(20) NOT NULL COMMENT '用户默认收货地址信息记录ID',
  role TINYINT(1) NOT NULL COMMENT '用户角色：0-管理员，1-用户',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY(id),
  UNIQUE KEY idx_username(username) USING BTREE
) ENGINE=INNODB AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8 COMMENT='用户信息表';

DROP TABLE IF EXISTS product_category;
CREATE TABLE product_category (
  id INT NOT NULL AUTO_INCREMENT COMMENT '产品品类ID',
  category_name VARCHAR(50) NOT NULL COMMENT '产品品类名称',
  parent_id INT NOT NULL COMMENT '父品类ID',
  status TINYINT(1) NOT NULL DEFAULT 1 COMMENT '品类状态：0-禁用，1-启用',
  op_id INT NOT NULL COMMENT '操作用户ID',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY(id)
) ENGINE=INNODB AUTO_INCREMENT=200 DEFAULT CHARSET=utf8 COMMENT='产品品类信息表';

DROP TABLE IF EXISTS product;
CREATE TABLE product (
  id INT NOT NULL AUTO_INCREMENT COMMENT '产品ID',
  product_name VARCHAR(100) NOT NULL COMMENT '产品名称',
  subtitle VARCHAR(200) DEFAULT NULL COMMENT '产品副标题',
  detail TEXT DEFAULT NULL COMMENT '产品详情',
  category_id INT NOT NULL COMMENT '产品二级品类ID',
  category_parent_id INT NOT NULL COMMENT '产品一级品类ID',
  status TINYINT(1) NOT NULL DEFAULT 1 COMMENT '产品状态：0-下线，1-在售',
  price DECIMAL(20, 2) NOT NULL DEFAULT 0 COMMENT '产品单价',
  stock_num INT NOT NULL DEFAULT 0 COMMENT '产品库存余位',
  main_img VARCHAR(500) DEFAULT NULL COMMENT '产品主图url',
  sub_img TEXT DEFAULT NULL COMMENT '产品副图json',
  op_id INT NOT NULL COMMENT '操作用户ID',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY(id)
) ENGINE=INNODB AUTO_INCREMENT=200 DEFAULT CHARSET=utf8 COMMENT='产品信息表';

DROP TABLE IF EXISTS logistics_info;
CREATE TABLE logistics_info (
  id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '物流信息记录ID',
  user_id INT NOT NULL COMMENT '所属用户ID',
  receiver_name VARCHAR(20) NOT NULL COMMENT '收货人姓名',
  receiver_phone VARCHAR(20) NOT NULL COMMENT '收货人联系电话',
  province VARCHAR(20) NOT NULL COMMENT '所属省份',
  city VARCHAR(20) NOT NULL COMMENT '所属市级单位',
  district VARCHAR(20) NOT NULL COMMENT '所属区/县',
  address VARCHAR(20) NOT NULL COMMENT '详细地址',
  zip_code VARCHAR(6) DEFAULT NULL COMMENT '邮政编码',
  status TINYINT(1) NOT NULL DEFAULT 1 COMMENT '物流信息记录状态：0-删除，1-用户默认收货地址，2-用户收货地址',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY(id)
) ENGINE=INNODB AUTO_INCREMENT=200 DEFAULT CHARSET=utf8 COMMENT='物流信息表';

DROP TABLE IF EXISTS user_cart;
CREATE TABLE user_cart (
  id INT NOT NULL AUTO_INCREMENT COMMENT '购物车记录ID',
  user_id INT NOT NULL COMMENT '所属用户ID',
  product_id INT NOT NULL COMMENT '产品ID',
  quantity INT NOT NULL COMMENT '购买产品数量',
  status TINYINT(1) NOT NULL DEFAULT 1 COMMENT '购物车记录状态：0-删除，1-未删除',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY(id)
) ENGINE=INNODB AUTO_INCREMENT=200 DEFAULT CHARSET=utf8 COMMENT='用户购物车记录表';

DROP TABLE IF EXISTS order_info;
CREATE TABLE order_info (
  id INT NOT NULL AUTO_INCREMENT COMMENT '订单信息记录ID',
  order_no BIGINT(20) NOT NULL COMMENT '订单流水号',
  user_id INT NOT NULL COMMENT '所属用户ID',
  order_payment DECIMAL(20, 2) NOT NULL COMMENT '订单总金额',
  reduction DECIMAL(20, 2) NOT NULL COMMENT '优惠金额',
  logistics_id BIGINT(20) NOT NULL COMMENT '用户收货地址信息记录ID',
  status TINYINT(1) NOT NULL DEFAULT 1 COMMENT '订单状态：0-已取消，1-未付款，2-已付款，3-已发货，4-已收货，5-交易完成，6-已退货，7-交易关闭',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY(id),
  UNIQUE KEY idx_order_no(order_no) USING BTREE
) ENGINE=INNODB AUTO_INCREMENT=200 DEFAULT CHARSET=utf8 COMMENT='订单信息表';

DROP TABLE IF EXISTS order_item;
CREATE TABLE order_item (
  id INT NOT NULL AUTO_INCREMENT COMMENT '订单构成详情记录ID',
  order_no BIGINT(20) NOT NULL COMMENT '所属订单流水号',
  product_id INT NOT NULL COMMENT '产品ID',
  quantity INT NOT NULL COMMENT '订单项产品购买数量',
  price DECIMAL(20, 2) NOT NULL COMMENT '下单时产品单价',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY(id)
) ENGINE=INNODB AUTO_INCREMENT=200 DEFAULT CHARSET=utf8 COMMENT='订单构成详情表';

DROP TABLE IF EXISTS pay_info;
CREATE TABLE pay_info (
  id INT NOT NULL AUTO_INCREMENT COMMENT '支付记录ID',
  user_id INT NOT NULL COMMENT '所属用户ID',
  order_no INT NOT NULL COMMENT '所属订单流水号',
  pay_way INT NOT NULL COMMENT '支付方式：1-支付宝，2-微信',
  payment DECIMAL(20, 2) NOT NULL COMMENT '支付金额',
  status TINYINT(1) NOT NULL DEFAULT 1 COMMENT '支付状态：0-未支付，1-已支付',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY(id)
) ENGINE=INNODB AUTO_INCREMENT=200 DEFAULT CHARSET=utf8 COMMENT='支付信息表';